### ISSUE TITLE
bypass battery

### ISSUE THREAD

**Issue by davidbono** [Xinyuan-LilyGO/LilyGO-T-Beam#16]
Hello,

I would like to use a 5v power supply(1,5A -5v) and by-passing the battery which I don't need. Do I have to go through USB ? Or any PIN ( VIN) available ?

Thank you

David

**Comment by lewisxhe** [comment]
There is a 5V input interface above the USB port, which can be directly accessed from there, or you can use USB input

**Comment by davidbono** [comment]
Thanks for your reply. 

![image](https://user-images.githubusercontent.com/11843274/81466429-f43c3400-91d1-11ea-9979-a6bb6497aa5e.png)

Do you mean this one ? If yes, will give another try.

**Comment by lewisxhe** [comment]
Yes it is here
