### ISSUE TITLE
How to measure battery level?

### ISSUE THREAD

**Issue by andrecurvello** [Xinyuan-LilyGO/LilyGO-T-Beam#17]
Hello,

There is any example on how to measure the battery level of hte TTGO T-Beam?

Thank you.

**Comment by andrecurvello** [comment]
False alarm...

**Comment by jhon-andrew** [comment]
@andrecurvello I also have the same question. Have you found any guide to measure the battery level?

**Comment by jangrewe** [comment]
Use the "official" library: https://github.com/lewisxhe/AXP202X_Library/blob/master/src/axp20x.cpp#L325
