### ISSUE TITLE
Charging 18650

### ISSUE THREAD

**Issue by kaelsaes** [Xinyuan-LilyGO/LilyGO-T-Beam#19]
Hi,

sorry for that newbie question but is it possible to charge the 18650 via the micro USB port?

Thanks

**Comment by lewisxhe** [comment]
Yes, that’s how he uses it

**Comment by jhon-andrew** [comment]
I have a follow up question regarding 18650 battery.

How can I identify the current battery level?

I'm using the T22_V07 board.

**Comment by kaelsaes** [comment]
> Yes, that’s how he uses it

Thanks

**Comment by lewisxhe** [comment]
@jhon-andrew v07 does not have PMU, but ADC resistance, you can check the schematic


![1](https://user-images.githubusercontent.com/22990954/84609295-fab47e80-aee8-11ea-8a32-dc2ad29abc46.jpg)

**Comment by CristalLagoons-BArratia** [comment]
How about using a solar panel to maintain it working for months? Anyone has any experience with it?
