### ISSUE TITLE
WiFi not working

### ISSUE THREAD

**Issue by zodiac-maniac** [Xinyuan-LilyGO/LilyGO-T-Beam#2]
Hi, I have an older T-Beam that works fine  with SoftRF and now received some new t-beams with revision T22_V10 20190612.
When I power them up, no led is blinking but they need 0.125mA. GPS led starts flashing after a while but I still get no WiFi signal. SoftRF should be preinstalled but I am worried that I get no WiFi signal. This is with 2 devices of this revision. Does anyone know how to activate WiFi or is lillygo producing it without SoftRF now?

**Comment by robstermn** [comment]
Did you find an solution to the WiFi issue?

**Comment by zodiac-maniac** [comment]
Yes, I wrote Lilygo to take care that all delivered t-beams should have a firmware installed already.
