### ISSUE TITLE
GPS problems...

### ISSUE THREAD

**Issue by CristalLagoons-BArratia** [Xinyuan-LilyGO/LilyGO-T-Beam#20]
Hi! I have two t-beam with the AXP192 chip and I'm struggling to achieve GPS information. The OLED is working and the LoRa functionality too, I can send and receive messages, but when trying to get any GPS data it keeps saying "Positioning" and then change to "NO GPS detected". 
I tried disconnecting the OLED display and checking the serial monitor, here is what it says:

> 
![image](https://user-images.githubusercontent.com/66485310/85242471-28c82000-b40d-11ea-804d-4e1f0909918e.png)

Please help! 

Thanks in advance :)

**Comment by CristalLagoons-BArratia** [comment]
Solved, It was a I2C problem...

**Comment by Zapfmeister** [comment]
What exactly was the issue?

**Comment by CristalLagoons-BArratia** [comment]
It was a while ago, but I think that it was a problem with the TX and RX pins, I switched them and It worked (I think I was using a bad or old image for reference)

**Comment by CristalLagoons-BArratia** [comment]
> What exactly was the issue?

It was a while ago, but I think that it was a problem with the TX and RX pins, I switched them and It worked (I think I was using a bad or old image for reference)
