### ISSUE TITLE
是否可以直接使用 6V 5W 的太阳能电池板充电？

### ISSUE THREAD

**Issue by catoc** [Xinyuan-LilyGO/LilyGO-T-Beam#23]

**Comment by lewisxhe** [comment]
不能直接把太阳能板直接接入，需要有太阳能充电管理才可以接入

**Comment by catoc** [comment]
> AXP192 的智慧电能平衡(Intelligent Power Select, IPS™)电路可以在USB 以及外部交流适配器、锂电
池和应用系统负载之间安全透明的分配电能，并且在只有外部输入电源而没有电池(或者电池过放/损坏)
的情况下也可以使应用系统正常工作。

Hi lewisxhe，请问：

1.  假设太阳能电池板作为 外部交流适配器的电源输入 AXP192 是否可以自动分配电能并完成充电管理的功能？
2. 如果不能话，是否使用类似 CN3165 这类可做电压源的太阳能充电管理芯片作为 外部的交流适配器电源输入？
3. 能否推荐一款完成此功能的芯片，我想和 AXP912 PMU 配合，获得更好的电源管理效果。

感谢！🙏

**Comment by lewisxhe** [comment]
你可以从原理图中看出，并没有把适配端单独在板子引出 ，你引用手册上的话，并不能实现。只能从vbus端接入电源 。


1. 不可能做到 ，硬件上没那么设计
2.可以，相当于外部充电管理负责充电，而192 只负责电压控制 
3. CN3165 就可以 ！

**Comment by catoc** [comment]
清楚了。
