### ISSUE TITLE
How to configure LORA credentials ?

### ISSUE THREAD

**Issue by vincegre** [Xinyuan-LilyGO/LilyGO-T-Beam#24]
Hi

I'd like to use this code with LilyGO-T-Beam V1.1 but I'm unable to find in code where I should put my LORA credentials !! I'm using the TTN (The Things Network) to receive data sent by the LilyGO-T-Beam !

Thanks

Vincèn

**Comment by phfu** [comment]
Hello,  this code is using LoRa transmission, just the radio protocol,  not the LoRaWAN network.
There is no way to connect to LoRaWAN network such as TTN with this code,  please see other codes such as TTN Mapper :) 

Regards
Philippe

**Comment by lewisxhe** [comment]
The sample code has been updated. The problem has not been updated for a long time and will be closed
