### ISSUE TITLE
Upload sketch error

### ISSUE THREAD

**Issue by pbravoz2** [Xinyuan-LilyGO/LilyGO-T-Beam#29]
Hi there, can anybody help me for this issue??:  uploading the sketch to T-Beam throws me the classic ESP32 error: **Failed to connect to ESP32: Timed out waiting for packet header**. The solution for the other ESP32 boards is to place a 10uF capacitor between the EN PIN and GND. But **T-Beam doesn't have the EN pin!** How can I solve it?. My T-Beam version is 1.0

I am very thankfull for your help.
Greetings, Pedro

**Comment by lewisxhe** [comment]
You can try it like this,
IO0 is shorted to GND, then press reset, then click upload

**Comment by pbravoz2** [comment]
Hi lewisxhe, it works perfect. The order is:

-IO0 shorted to GND
-reset (it boots in a special mode waiting for upload)
-upload the sketch
-disconnect IO0 from GND
-reset to normal boot

Thank you!!
