### ISSUE TITLE
Compile Error : axp20x.h: No such file or directory

### ISSUE THREAD

**Issue by MJSM-AEC** [Xinyuan-LilyGO/LilyGO-T-Beam#30]
Hi guys,
I am new to this product. I downloaded the "https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/tree/master/examples/gps" file to test GPS module.
I got error  "gps:4:20: fatal error: axp20x.h: No such file or directory"
How to find all requirements?
Regards

**Comment by lewisxhe** [comment]
你是否使用arduino ide  ？ 需要依赖一些库 ，具体列表请在这里查看

https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/blob/master/platformio.ini

**Comment by lewisxhe** [comment]
The problem has not been updated for a long time and will be closed...
