### ISSUE TITLE
csum error - sometimes

### ISSUE THREAD

**Issue by roema** [Xinyuan-LilyGO/LilyGO-T-Beam#31]
Hi!

I have a problem with one T-Beam. Sometimes he wont boot. Bootloader and software are ok. The second Beam works perfect. I think, its a hardware problem to read the spi flash correctly!

When i restart the beam, sometimes it comes up...

Thank for your message

![T-Beam](https://user-images.githubusercontent.com/9306994/96710842-eacc1000-139c-11eb-84b8-6e958e5ad26f.png)

**Comment by lewisxhe** [comment]
If the burning is normal, then the flash should be damaged, if possible, you can replace a flash and try

**Comment by lewisxhe** [comment]
The problem has not been updated for a long time and will be closed...
