### ISSUE TITLE
AFSK on T-Beam V1.1 with SX1278

### ISSUE THREAD

**Issue by raufaser** [Xinyuan-LilyGO/LilyGO-T-Beam#32]
Hello everyone,

I am trying to do AFSK with my T-Beam. I am using the RadioLib to do so. Unfortunately I am only getting an unmodulated carrier. I already posted a similar question on the RadioLib's Github. This issue can be found [here](https://github.com/jgromes/RadioLib/issues/190)

Since this seems to be a very board specific topic i am now trying to get help from you guys.

There are Pins on the board which are called Lora1 and Lora2. Am i right that there are connected to the SX1278 DIO1 and DIO2? And am I right that there are also connected to Pins 33 and 32?

I would really appreciate any help.

**Comment by lewisxhe** [comment]
![1](https://user-images.githubusercontent.com/22990954/97397811-0f883080-1925-11eb-9d07-40f969af46d9.png)
From the schematic, it is connected 32, 33

https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/blob/master/schematic/LilyGo_TBeam_V1.1.pdf
