### ISSUE TITLE
Measuring the transmitter power of the SX1262 chip

### ISSUE THREAD

**Issue by nickfrost73** [Xinyuan-LilyGO/LilyGO-T-Beam#35]
I thought the LoRa transmitter of SX1262 chip can produce 22dBm. I measured the power with two spectrum analyzers and the power is no more than 12dBm. It's a pity that I can't attach images here. Can anyone do the same to check the power? I suppose that if TX power was as promised, I would reach a much longer distance.

**Comment by lewisxhe** [comment]
I can’t answer this question. This is a hardware manufacturing issue. Issues have not been active for a long time and will be closed.
