### ISSUE TITLE
Compile error - Allfunction.ino

### ISSUE THREAD

**Issue by smarti2019** [Xinyuan-LilyGO/LilyGO-T-Beam#37]
AllFunction:84:30: error: no matching function for call to 'Button2::Button2()'

     pBtns = new Button2 [args];

**Comment by phfu** [comment]
Hello
I replaced the code with : 
pBtns = new Button2 (BUTTONS_MAP);
and it worked.   It's a bit confusing just for handling one button.

Anyhow, it is then possible to switch betweeb the 3 screens.

GPS works,  LoRa transmission also (I can see the packet on an spectrum analyser) but receiver is not working.
With 2 modules, one TX, other RX,   RX not working,  even when switching the 2 devices.

Regards
Philippe

**Comment by lewisxhe** [comment]
The sample code has been updated, please update, it should be easier to understand than the original

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed
