### ISSUE TITLE
"ArduinoLoRa" example not work with "T-Beam V1.1 SX1262 LORA"

### ISSUE THREAD

**Issue by izzet-kalinsazlioglu** [Xinyuan-LilyGO/LilyGO-T-Beam#38]
T Beam "ArduinoLoRa" this example use <LoRa.h> library .  
but  this library 
https://github.com/sandeepmistry/arduino-LoRa
not support yet SX1262 LORA chips. 

message is : Starting LoRa failed!

**Comment by lyusupov** [comment]
This is not true.

T-Beam [SX1262-specific examples](https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/tree/master/examples/SX1262) are using [RadioLib](https://github.com/jgromes/RadioLib) instead:
https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/blob/master/examples/SX1262/SX126x_Receive_Interrupt/SX126x_Receive_Interrupt.ino#L20

RadioLib has declared support for SX162 radio:
https://github.com/jgromes/RadioLib#supported-modules

**Comment by izzet-kalinsazlioglu** [comment]
@lyusupov thank you. it works.  I solved with some warnings. 
current problem is . I need Lora module pinouts on this page 
https://www.aliexpress.com/item/4000542688096.html?spm=a2g0o.cart.0.0.6eee3c00vKLQsQ&mp=1
because pin numbers are not explained.
#define LORA_DI0        ??
#define LORA_DIO1       ??
#define LORA_BUSY       ??

i try . it works with some warnings.
#define LORA_DI0        33
#define LORA_DIO1       32
#define LORA_BUSY       34

or 
How can i fix this lora library for sx1262 support. 
https://github.com/sandeepmistry/arduino-LoRa

![Lora Target System](https://user-images.githubusercontent.com/13614048/101383099-00e45000-38b9-11eb-8893-3699fcd9dff4.jpg)

![problem](https://user-images.githubusercontent.com/13614048/101387371-a3eb9880-38be-11eb-9f65-7a84cc0ef362.png)

**Comment by lewisxhe** [comment]
arduino-LoRa does not support 1262, you can use radiolib

**Comment by dragosmacovei** [comment]
> Your statement is not correct.
> 
> T-Beam [SX1262-specific examples](https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/tree/master/examples/SX1262) are using [RadioLib](https://github.com/jgromes/RadioLib) instead:
> https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/blob/master/examples/SX1262/SX126x_Receive_Interrupt/SX126x_Receive_Interrupt.ino#L20
> 
> RadioLib has declared support for SX1262 radio:
> https://github.com/jgromes/RadioLib#supported-modules
> 
> So you need to pre-install the RadioLib in order to use SX1262 specific examples with this particular T-Beam variant.
> A copy of the RadioLib is already located in [libdeps](https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam/tree/master/libdeps) folder of this GitHub repo.

The link for git is not working anymore

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed
