### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by robstermn** [Xinyuan-LilyGO/LilyGO-T-Beam#4]
I uploaded the example and I get not response from BTN 2, the units just keeps on sending?
See picture for model of the TTGO.

![image](https://user-images.githubusercontent.com/9891262/71632480-63769b80-2bd4-11ea-8144-499c8c8dc674.png)

**Comment by lewisxhe** [comment]
Click button 2 will cycle the motherboard function, the default start to enable GPS positioning, the second click will be set to lora send, the third click will be set to lora receive, long press for two seconds and then release, will enter deep sleep

**Comment by robstermn** [comment]
I finally got it working with an arduino IDE, but I can't seem to get it to compile with VSCode/PlatformIO?  I'm getting the following errors:

`
class "LoRaClass" has no member "setPins"
class "LoRaClass" has no member "begin"
class "LoRaClass" has no member "beginPacket"
class "LoRaClass" has no member "print"
class "LoRaClass" has no member "endPacket"
class "LoRaClass" has no member "parsePacket"
class "LoRaClass" has no member "available"
class "LoRaClass" has no member "read"
class "LoRaClass" has no member "packetRssi"
class "LoRaClass" has no member "packetRssi"

`
