### ISSUE TITLE
FAILURE 

### ISSUE THREAD

**Issue by dragosmacovei** [Xinyuan-LilyGO/LilyGO-T-Beam#43]
```
initBoard
LoRa Receiver

C:\Users\USERNAME\OneDrive\Documents\Arduino\libraries\LMIC-Arduino\src\lmic\radio.c:691
```

This is the output I get with TTN_OTTA example on TTGO T-Beam. I did tried to 

```
#define CFG_eu868 1
//#define CFG_us915 1
// This is the SX1272/SX1273 radio, which is also used on the HopeRF
// RFM92 boards.
#define CFG_sx1272_radio 1
// This is the SX1276/SX1277/SX1278/SX1279 radio, which is also used on
// the HopeRF RFM95 boards.
//#define CFG_sx1276_radio 1
```

change from `CFG_sx1272_radio  `to `CFG_sx1276_radio ` but the other ASSERT fails

```
#ifdef CFG_sx1276_radio
    ASSERT(v == 0x12 );
#elif CFG_sx1272_radio
    ASSERT(v == 0x22 );
#else
#error Missing CFG_sx1272_radio/CFG_sx1276_radio
#endif
```

- Region (EU868)
- Radio (SX1276 - I believe, not sure how to find out)
- Arduino: 1.8.14 Hourly Build 2020/12/15
- Os: (Windows 10)
- Board: "TTGO T1" (TTGO T-Beam v1.1) Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600

**Comment by lewisxhe** [comment]
If you use arduino ide, you need to rename TTN_OTTA.cpp to TTN_OTTA.ino. I did not report an error on my computer!
![short](https://user-images.githubusercontent.com/22990954/103388799-06def100-4b46-11eb-8f7d-6cc332a058ed.png)

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed
