### ISSUE TITLE
AXP Overheating

### ISSUE THREAD

**Issue by blenderlab** [Xinyuan-LilyGO/LilyGO-T-Beam#5]
Hello, I have 12 TBeam (T22_v1.1) , and 2 of them went on overheating the AXP. They can boot, then disapear from USB list. One used a 18650 battery, the second was'nt. 
Is there a fuse or resistor problem possible ? 
Thanks.

**Comment by SeungRyeol** [comment]
I have the same symptoms. The board is broken.

**Comment by blenderlab** [comment]
So it seems to be a conception issue....

**Comment by lewisxhe** [comment]
Can you provide clear pictures of the following boards? @blenderlab @SeungRyeol
